import { pgEnum } from "drizzle-orm/pg-core";
import * as d from "@/lib/domain";

export const startupStageEnum = pgEnum("startup_stage", d.STARTUP_STAGES);
export const commitmentEnum = pgEnum("commitment", d.COMMITMENTS);
export const availabilityEnum = pgEnum("availability", d.AVAILABILITY);
export const workModeEnum = pgEnum("work_mode", d.WORK_MODES);
export const ambitionEnum = pgEnum("ambition", d.AMBITIONS);
export const founderExperienceEnum = pgEnum("founder_experience", d.FOUNDER_EXPERIENCE);
export const visibilityEnum = pgEnum("visibility", d.VISIBILITY);
export const accountStatusEnum = pgEnum("account_status", d.ACCOUNT_STATUSES);
export const fundingStatusEnum = pgEnum("funding_status", d.FUNDING_STATUSES);
export const startupMemberRoleEnum = pgEnum("startup_member_role", d.STARTUP_MEMBER_ROLES);
export const needTypeEnum = pgEnum("need_type", d.NEED_TYPES);
export const needStatusEnum = pgEnum("need_status", ["open", "paused", "fulfilled", "closed"]);
export const pricingTypeEnum = pgEnum("pricing_type", d.PRICING_TYPES);
export const bookingStatusEnum = pgEnum("booking_status", d.BOOKING_STATUSES);
export const paymentStatusEnum = pgEnum("payment_status", d.PAYMENT_STATUSES);
export const conversationTypeEnum = pgEnum("conversation_type", d.CONVERSATION_TYPES);
export const messageKindEnum = pgEnum("message_kind", ["text", "image", "file", "system"]);
export const connectionStatusEnum = pgEnum("connection_status", ["pending", "accepted", "declined", "withdrawn"]);
export const interestKindEnum = pgEnum("interest_kind", ["interested", "passed"]);
export const recommendationActionEnum = pgEnum("recommendation_action", ["none", "passed", "saved", "interested"]);
export const consultantStatusEnum = pgEnum("consultant_status", ["draft", "pending_review", "approved", "rejected", "suspended"]);
export const inviteStatusEnum = pgEnum("invite_status", ["pending", "accepted", "declined", "revoked", "expired"]);
export const verificationTypeEnum = pgEnum("verification_type", d.VERIFICATION_TYPES);
export const verificationStatusEnum = pgEnum("verification_status", ["pending", "verified", "rejected", "expired"]);
export const reportTargetEnum = pgEnum("report_target", d.REPORT_TARGETS);
export const reportReasonEnum = pgEnum("report_reason", d.REPORT_REASONS);
export const reportStatusEnum = pgEnum("report_status", ["open", "reviewing", "actioned", "dismissed"]);
export const saveTargetEnum = pgEnum("save_target", d.SAVE_TARGETS);
export const adminRoleEnum = pgEnum("admin_role", d.ADMIN_ROLES);
export const waitlistStatusEnum = pgEnum("waitlist_status", ["waiting", "invited", "joined"]);
export const reviewStatusEnum = pgEnum("review_status", ["published", "hidden"]);
export const followTargetEnum = pgEnum("follow_target", ["user", "startup"]);
export const aiRoleEnum = pgEnum("ai_role", ["user", "assistant"]);
